name: Discussions â†’ Telegram

on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar nueva discusiÃ³n (texto plano)
        if: github.event_name == 'discussion' && github.event.action == 'created'
        uses: appleboy/telegram-action@v1.0.1
        with:
          token: ${{ secrets.BOT_TOKEN }}
          to: ${{ secrets.CHAT_ID }}
          message: |
            ğŸš€  Nueva Pregunta en el Foro ğŸš€

            ğŸ“ Repositorio: ${{ github.repository }}

            ğŸ“ TÃ­tulo: ${{ github.event.discussion.title }}

            ğŸ‘¤ Autor: ${{ github.event.discussion.user.login }}

            ğŸ“ Contenido:
            ${{ github.event.discussion.body }}

            ğŸ”— Enlace: ${{ github.event.discussion.html_url }}

      - name: Notificar comentario en discusiÃ³n
        if: github.event_name == 'discussion_comment' && github.event.action == 'created'
        uses: appleboy/telegram-action@v1.0.1
        with:
          token: ${{ secrets.BOT_TOKEN }}
          to: ${{ secrets.CHAT_ID }}
          message: |
            ğŸ’¬ Nuevo Comentario en el Foro ğŸ’¬

            ğŸ“ DiscusiÃ³n: ${{ github.event.discussion.title }}

            ğŸ‘¤ Comentado por: ${{ github.event.comment.user.login }}

            ğŸ—’ï¸ Comentario:
            ${{ github.event.comment.body }}

            ğŸ”— Enlace: ${{ github.event.comment.html_url }}
